'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';

type Restaurant = { id: string; name: string; slug: string; description: string; address: string; primary_color: string; currency: string; item_count: number };

export default function BusinessDashboard({ apiUrl }: { apiUrl: string }) {
  const router = useRouter();
  const [restaurants, setRestaurants] = useState<Restaurant[]>([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { fetch(`${apiUrl}/api/admin/restaurants`, { credentials: 'include' }).then(async (response) => { if (response.status === 401) { router.replace('/login'); return; } const result = await response.json(); setRestaurants(result.data); setLoading(false); }); }, [apiUrl, router]);
  async function logout() { await fetch(`${apiUrl}/api/auth/logout`, { method: 'POST', credentials: 'include' }); router.push('/'); router.refresh(); }
  return <main className="min-h-screen bg-[#f4f0e8] text-[#1d2b25]"><header className="border-b border-black/8 bg-white"><div className="mx-auto flex h-20 max-w-6xl items-center justify-between px-4 sm:px-6"><Link className="font-serif text-2xl font-bold" href="/">Menuo</Link><button className="rounded-full border border-black/10 px-4 py-2 text-xs font-semibold" onClick={logout}>Вийти</button></div></header><section className="mx-auto max-w-6xl px-4 py-10 sm:px-6 sm:py-16"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#a36f38]">Ваш кабінет</p><h1 className="mt-3 font-serif text-4xl sm:text-6xl">Мої заклади</h1><p className="mt-3 text-sm text-black/50">Створюйте окреме QR-меню для кожної локації.</p></div><Link className="rounded-full bg-[#1f392d] px-6 py-3 text-center text-sm font-semibold text-white" href="/admin/new">+ Створити заклад</Link></div>{loading ? <p className="mt-12 text-sm text-black/45">Завантажуємо…</p> : restaurants.length ? <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{restaurants.map((restaurant) => <article className="rounded-3xl border border-black/10 bg-white p-6" key={restaurant.id}><span className="grid size-11 place-items-center rounded-full text-white" style={{ backgroundColor: restaurant.primary_color }}>{restaurant.name.charAt(0)}</span><h2 className="mt-5 font-serif text-2xl">{restaurant.name}</h2><p className="mt-2 text-sm text-black/45">{restaurant.address}</p><p className="mt-5 text-xs text-black/40">{restaurant.item_count} позицій · {restaurant.currency}</p><div className="mt-5 flex gap-2"><Link className="rounded-full bg-[#1f392d] px-4 py-2 text-xs font-semibold text-white" href={`/admin/${restaurant.slug}`}>Керувати</Link><Link className="rounded-full border border-black/10 px-4 py-2 text-xs font-semibold" href={`/${restaurant.slug}`}>Переглянути</Link></div></article>)}</div> : <div className="mt-10 rounded-3xl border border-dashed border-black/15 bg-white/60 p-10 text-center"><h2 className="font-serif text-2xl">Ще немає закладів</h2><p className="mt-2 text-sm text-black/45">Створіть перший — це займе кілька хвилин.</p></div>}</section></main>;
}
